DROP TABLE T_QUARTERS;
create table T_QUARTERS 
(
   QUARTER_ID               NUMBER,
   CALENDAR_QUARTER_NUMBER  NUMBER,
   DAYS_IN_CAL_QUARTER      NUMBER,
   END_CAL_QUARTER_DATE     DATE,
   BEG_CAL_QUARTER_DATE     DATE,
   constraint T_QUARTERS primary key (QUARTER_ID)
);